title: Rafael Araujo
description: Descrição do blog

url: https://rafaelcoquex.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [Rafael-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: https://rafaelcoquex.github.io/
  linkedin: www.linkedin.com/in/rafaelaraujodasilva
  email: raraujo.silva@yahoo.com.br


disqus:
    shortname: my-disqus-shortname
